#!/bin/bash
#jach

outdir=html

for f in years/*.bib
do
   echo $f
   filename=$(basename -- "$f")
   extension="${filename##*.}"
   year="${filename%.*}"
   echo $year
   bibtex2html --revkeys -nodoc -nobibsource -d -r -t $year -css style.css $f
   sed -i 's/<em>This file was generated by//g' $year.html  
   sed -i '/<a href="http:\/\/www.lri.fr\/~filliatr\/bibtex2html\/">bibtex2html<\/a> 1.99.<\/em><\/p>/d' $year.html  
   mv $year.html $outdir/
   cd $outdir 
   ls -r *.html | xargs cat > index.html
   cd ..
   cp html/index.html .
done

#bibtex2html --revkeys -d -r -t "UPLB Institute of Computer Science Publications" -css style.css index.bib
#rm *.aux *.bbl *.blg bib2html*
